dist: bionic
language: node_js
node_js:
  - 14.17.0
script: echo "Testing temporarily disabled"
deploy:
  provider: script
  script: bash scripts/deploy $AES_PASS
  on:
    branch: main
  skip_cleanup: true
branches:
  only:
    - main
    - development
